### ISSUE TITLE
Output?

### ISSUE THREAD

**Issue by brucearctor** [GoogleCloudPlatform/pubsubbeat#33] opened 2019-11-19 16:18 UTC
I would like a filebeat with pubsub output...   Should this be a different beat?  Or since this is called 'pubsubbeat' is it preferred that this handles both (input, as it does, as well as output)?

**Comment by josephlewis42** [comment] 2019-11-19 22:57
Hi @brucearctor, due to the way the beats are set up (each contain a duplicate of the beats library) each individual beat would need to support Pub/Sub output.

Historically, Elastic has been hesitant to add additional outputs to their beats for business purposes. Beats _do_ allow exporting to Redis and you could possibly wire up a fake Redis server that forwarded to Pub/Sub--the same could go for Kafka ([Google has a Kafka bridge](https://github.com/GoogleCloudPlatform/pubsub/tree/master/kafka-connector)). Or, if you have LogStash in your pipeline, you could ingest data from a beat to LogStash and forward it out using `logstash-output-google_pubsub`.

I did a little POC a while back that wrapped beats in with a fake server that mimicked the Redis protocol and it turned out pretty nicely. That could be an approach to try. Would it be possible to run two binaries together like that (one that sets up a fake server and wraps the other)?

**Comment by brucearctor** [comment] 2019-11-23 22:23
Thanks, @josephlewis42 , that is a cool idea (setup fake server, etc) -- while it also seems silly for that to be necessary.  For example, for my use case, I am happy to write filebeat -> pubsub output.  Writing contacts at Elastic now to figure out whether this can be accepted, or to understand justification of why it wouldn't be.

**Closed** 2020-06-19 17:18 UTC
Labels: enhancement, question, wontfix
